# Generated by Django 5.2.4 on 2025-07-11 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='uploaded_by',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='liked_by',
        ),
        migrations.AlterField(
            model_name='photo',
            name='tags',
            field=models.ManyToManyField(blank=True, to='photos.tag'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
